[package]
name = "rdf_worker"
version = "0.1.3"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11"
pretty_env_logger = "0.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.9"
rdf_translator = {git = "https://github.com/media-io/rdf_translator"}
