[package]
name = "rdf_worker"
version = "0.1.3"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.12"
pretty_env_logger = "0.2"
reqwest = "0.9.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
amqp_worker = "0.1.4"
rdf = "0.1.4"
